language: python
python: "2.7"
env:
    global:
        - IS_TRAVIS=true
    matrix:
        - DAV_SERVER=radicale_filesystem REQUIREMENTS=release
        - DAV_SERVER=radicale_filesystem REQUIREMENTS=devel
        - DAV_SERVER=radicale_database REQUIREMENTS=release
        - DAV_SERVER=radicale_database REQUIREMENTS=devel
        - DAV_SERVER=owncloud REQUIREMENTS=release

install:
    - "./install-deps.sh"
    - "pip install coveralls"
script:
    - "coverage run --source=vdirsyncer/,tests/ --module pytest"
    - "coverage report --show-missing"
    - "travis_retry coveralls"

matrix:
    allow_failures:
        # radicale db storage is broken in 0.8
        - env: DAV_SERVER=radicale_database REQUIREMENTS=release
        - env: DAV_SERVER=owncloud REQUIREMENTS=release
