language: python
python:
    - "2.7"
    - "3.3"
env:
    matrix:
        - BUILD=tests DAV_SERVER=radicale RADICALE_BACKEND=filesystem REQUIREMENTS=release
        - BUILD=tests DAV_SERVER=radicale RADICALE_BACKEND=filesystem REQUIREMENTS=devel
        - BUILD=tests DAV_SERVER=radicale RADICALE_BACKEND=database REQUIREMENTS=devel
        - BUILD=tests DAV_SERVER=owncloud REQUIREMENTS=release
        - BUILD=style

install:
    - "./build.sh install"
script:
    - "./build.sh run"
