language: python
python: "2.7"
env:
    global:
        - IS_TRAVIS=true
    matrix:
        - DAV_SERVER=radicale RADICALE_BACKEND=filesystem REQUIREMENTS=release
        - DAV_SERVER=radicale RADICALE_BACKEND=filesystem REQUIREMENTS=devel
        - DAV_SERVER=radicale RADICALE_BACKEND=database REQUIREMENTS=devel
        - DAV_SERVER=owncloud REQUIREMENTS=release

install:
    - "./install-deps.sh"
    - "pip install coveralls"
script:
    - "coverage run --source=vdirsyncer/,tests/ --module pytest"
    - "travis_retry coveralls"
