language: python
python: "2.7"
env:
    - DAV_SERVER=radicale RADICALE_STORAGE=filesystem
    - DAV_SERVER=radicale RADICALE_STORAGE=database
    - DAV_SERVER=radicale_git RADICALE_STORAGE=filesystem
    - DAV_SERVER=radicale_git RADICALE_STORAGE=database

install:
    - "sh install-deps.sh"

script: py.test
