language: python
python: "2.7"
env:
    global:
        - IS_TRAVIS=true
    matrix:
        - DAV_SERVER=radicale_filesystem REQUIREMENTS=release
        - DAV_SERVER=radicale_filesystem REQUIREMENTS=devel
        - DAV_SERVER=radicale_database REQUIREMENTS=release
        - DAV_SERVER=radicale_database REQUIREMENTS=devel
        - DAV_SERVER=owncloud REQUIREMENTS=release

install: "./install-deps.sh"
script: "./run-tests.sh tests/"
